# Generated by Django 4.2.7 on 2023-12-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
    ]
