# Generated by Django 4.2.7 on 2023-12-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avatar',
        ),
    ]
