# Generated by Django 4.2.7 on 2023-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, default='default-room-avatar.png', null=True, upload_to=''),
        ),
    ]
