# Generated by Django 4.2.7 on 2023-12-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avatar',
        ),
    ]
