# Generated by Django 4.2.7 on 2023-12-25 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0008_room_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='room_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
