# Generated by Django 4.2.7 on 2023-12-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_room_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created', '-updated')},
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
