# Generated by Django 4.2.7 on 2024-01-01 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_room_options_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
